version: 2

defaults: &defaults
  environment:
    NODE_ENV: development
  working_directory: ~/style-guide
  docker:
    - image: circleci/node:8

jobs:
  build:
    <<: *defaults
    steps:
      - checkout

      - restore_cache:
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}

      - run: yarn install
      - run: lerna bootstrap

      - save_cache:
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

      - run: yarn flow

      - run: yarn lint

      - run: yarn test --runInBand
